### PR TITLE
add selection of easing functions

### PR DESCRIPTION
**Pull request by juliusberger**
Added and tested common easing functions from https://easings.net/en.
Remarks:
- Changed the settings layout for easing settings
- Included third-party easing functions from https://github.com/warrenm/AHEasing
- "Elastic", "Bounce" and "Back" easing functions don't work properly, since `t` is exceeding 0 (or 1) with these functions. So marked them as "EXPERIMENTAL" for now
- Dutch translations need to be adapted

### CODE REVIEW

**Comment by juliusberger** [comment]
- [ ] update readme

**Comment by juliusberger** [comment]
could be, that I missed adapting the CMakeLists.txt. I am not familiar with this whole C build system

**Comment by exeldro** [comment]
Thank you for the pull request, I will try and make it work later this week.
I will edit the CMakeLists.txt and dutch translations and test the experimental easings.

**Comment by juliusberger** [comment]
I tried to do the job with CMakeLists.txt. Maybe it was that simple

**Pull request merged**
