### PR TITLE
add macOS packaging project

### PR DESCRIPTION
**Pull request by PatTheMav**
Default packaging script to create package installers on macOS.

### CODE REVIEW

**Comment by exeldro** [comment]
Can you describe how this file should be used?

**Comment by PatTheMav** [comment]
You can use this in CI scripts to generate macOS package installers for you.

So you can have one part of your CI scripts check and install the Packages app:

```
HAS_PACKAGES=$(type packagesbuild 2>/dev/null)

if [ "${HAS_PACKAGES}" = "" ]; then
    curl -o './Packages.pkg' --retry-connrefused -s --retry-delay 1 'https://s3-us-west-2.amazonaws.com/obs-nightly/Packages.pkg'
    sudo installer -pkg ./Packages.pkg -target /
fi
```

Then after the plugin was successfully built, create the package via:

```
packagesbuild ./CI/macos/obs-websocket.pkgproj
```

With this you could have macOS installers e.g. created by GitHub Actions without access to a macOS system.

**Comment by exeldro** [comment]
I made part of a github workflow using your github workflow pull request for obs. But I don't know enough of Mac packaging to finish that part.
Can you help me with that?
https://github.com/exeldro/obs-move-transition/commit/15e5d64fc075ded9153372ff694f4d31d98a0432

**Comment by PatTheMav** [comment]
@exeldro Sure, I'll look into creating a working macOS workflow tomorrow.

**Pull request merged**
